### ISSUE TITLE
Enabling CAS features: integration vs support

### ISSUE THREAD

**Issue by mmoayyed** [UniconLabs/cas-plugin-dev#2]
Adopt a cas-agnostic way of enabling features instead of "integration vs support".

**Comment by dima767** [comment]
Note that currently in CAS `master` there are no more `integration` sub-projects. They are ALL (for the most part) `cas-server-support-*`

**Comment by dima767** [comment]
And so, there are `support` subprojects and there are also `core` subprojects like for example `cas-server-core-events-jpa`, `cas-server-core-events-mongo`, `cas-server-core-tickets`, etc. So, perhaps 2 distinct DSL elements like `feature` and `core` to differentiate those (and not sure if it's possible implementation-wise otherwise):

``` groovy
cas {
    version '5.0.0'
    core 'events-mongo'
    core 'tickets'
    feature 'hazelcast-ticket-registry'
    feature 'jpa-service-registry'
}
```
